# Generated by Django 5.0.6 on 2025-10-30 00:17

import django.db.models.deletion
import django_ulidfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blackout',
            fields=[
                ('blackout_id', django_ulidfield.fields.ULIDField(default=django_ulidfield.fields.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True, validators=[django_ulidfield.fields.validate_ulid])),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField(default=None)),
                ('description', models.CharField(default=None, max_length=256, null=True)),
                ('type', models.CharField(choices=[('HT', 'Heat'), ('HW', 'Hot water'), ('CW', 'Cold water'), ('EL', 'Electricity')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('building_id', django_ulidfield.fields.ULIDField(default=django_ulidfield.fields.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True, validators=[django_ulidfield.fields.validate_ulid])),
                ('number', models.IntegerField()),
                ('is_current', models.BinaryField()),
                ('coordinates', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='BuildingType',
            fields=[
                ('building_type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('building_type_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.IntegerField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('district_id', models.IntegerField(primary_key=True, serialize=False)),
                ('district_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='FolkDistrict',
            fields=[
                ('folk_district_id', models.IntegerField(primary_key=True, serialize=False)),
                ('folk_district_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Initiator',
            fields=[
                ('initiator_id', models.IntegerField(primary_key=True, serialize=False)),
                ('initiator_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('source_id', models.IntegerField(primary_key=True, serialize=False)),
                ('source_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('street_id', models.IntegerField(primary_key=True, serialize=False)),
                ('street_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='BlackoutBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blackout_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.blackout')),
                ('building_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.building')),
            ],
        ),
        migrations.AddField(
            model_name='building',
            name='building_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.buildingtype'),
        ),
        migrations.AddField(
            model_name='building',
            name='city_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.city'),
        ),
        migrations.AddField(
            model_name='building',
            name='district_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.district'),
        ),
        migrations.AddField(
            model_name='building',
            name='folk_district_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.folkdistrict'),
        ),
        migrations.AddField(
            model_name='blackout',
            name='initiator_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.initiator'),
        ),
        migrations.AddField(
            model_name='blackout',
            name='source_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.source'),
        ),
        migrations.AddField(
            model_name='building',
            name='street_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.street'),
        ),
    ]
