# Generated by Django 5.0.6 on 2025-10-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='is_current',
            field=models.BooleanField(),
        ),
    ]
