# Generated by Django 5.0.6 on 2025-10-30 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_building_is_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='number',
            field=models.CharField(max_length=64),
        ),
    ]
