# Generated by Django 5.0.6 on 2025-10-30 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_building_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blackout',
            name='end_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
