# Generated by Django 5.0.6 on 2025-11-05 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_blackout_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='street',
            name='street_city_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.city'),
        ),
    ]
