# Generated by Django 5.0.6 on 2025-11-05 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_street_street_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='street',
            name='street_name',
        ),
    ]
