# Generated by Django 5.0.6 on 2025-11-05 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_street_street_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='street',
            name='street_name',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='street',
            unique_together={('street_name', 'street_city_id')},
        ),
    ]
