# Generated by Django 5.0.6 on 2025-11-05 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_street_street_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='street',
            name='street_name',
            field=models.CharField(max_length=128),
        ),
    ]
