# Generated by Django 5.0.6 on 2025-11-05 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_street_street_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='street',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='street',
            name='street_name',
        ),
    ]
