# Generated by Django 5.0.6 on 2025-11-05 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_street_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='street',
            name='street_name',
            field=models.CharField(default='удалить', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='street',
            unique_together={('street_name', 'street_city_id')},
        ),
    ]
