# Generated by Django 5.0.6 on 2025-11-05 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_street_street_name_alter_street_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='street',
            name='street_name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
